blank_issues_enabled: true
contact_links:
  - name: Drinkaware Integration Documentation
    url: https://github.com/B-Hartley/drinkaware
    about: Please check the documentation before opening an issue.
