log_drink_free_day:
  name: Log drink-free day
  description: Mark a specific day as alcohol-free in your Drinkaware tracking
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use
      required: true
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware
    date:
      name: Date
      description: The date to mark as a drink-free day (defaults to today)
      required: false
      example: "2025-04-18"
      selector:
        date:
    remove_drinks:
      name: Remove Existing Drinks
      description: Automatically remove any existing drinks for the day before marking it as drink-free
      required: false
      default: false
      example: true
      selector:
        boolean:
        
log_drink:
  name: Log drink
  description: Record a drink in your Drinkaware tracking
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use
      required: true
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware
    # Remove the drink_type_selector field
    drink_id:
      name: Standard Drink Type
      description: "Select a standard drink type from the list (use this OR custom drink ID)"
      required: false
      example: "Lager"
      selector:
        select:
          options: !include drinkoptions.yaml
          mode: dropdown
    custom_drink_id:
      name: Custom Drink ID
      description: "Enter a custom drink ID (use this OR standard drink type)"
      required: false
      example: "12345678-ABCD-1234-5678-123456789ABC"
      selector:
        text:
    measure_id:
      name: Measure Type
      description: "The measure to use (make sure it's compatible with the selected drink type)"
      required: true
      example: "Pint"
      selector:
        select:
          options: !include measureoptions.yaml
          mode: dropdown
    name:
      name: Custom Name
      description: Optional custom name for the drink (only works with custom ABV)
      required: false
      example: "My Special IPA"
      selector:
        text:
    abv:
      name: ABV
      description: The alcohol percentage (optional, will use default if not specified)
      required: false
      example: 4.5
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: "%"
    quantity:
      name: Quantity
      description: The number of drinks of this type (defaults to 1)
      required: false
      example: 2
      selector:
        number:
          min: 1
          max: 99
          step: 1
    date:
      name: Date
      description: The date to log the drink (defaults to today)
      required: false
      example: "2025-04-18"
      selector:
        date:
    auto_remove_dfd:
      name: Auto Remove Drink-Free Day
      description: Automatically remove the drink-free day mark if present
      required: false
      default: false
      example: true
      selector:
        boolean:

delete_drink:
  name: Delete drink
  description: Remove a recorded drink from your Drinkaware tracking
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use
      required: true
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware
    # Remove the drink_type_selector field
    drink_id:
      name: Standard Drink Type
      description: "Select a standard drink type from the list (use this OR custom drink ID)"
      required: false
      example: "FAB60DBF-911F-4286-9C3E-0F0BCB40E3B7"
      selector:
        select:
          options: !include drinkoptions.yaml
          mode: dropdown
    custom_drink_id:
      name: Custom Drink ID
      description: "Enter a custom drink ID (use this OR standard drink type)"
      required: false
      example: "12345678-ABCD-1234-5678-123456789ABC"
      selector:
        text:
    measure_id:
      name: Measure Type
      description: "The measure of the drink to delete (must be compatible with the selected drink type)"
      required: true
      example: "Pint"
      selector:
        select:
          options: !include measureoptions.yaml
          mode: dropdown
    date:
      name: Date
      description: The date the drink was logged (defaults to today)
      required: false
      example: "2025-04-18"
      selector:
        date:
        
remove_drink_free_day:
  name: Remove drink-free day
  description: Remove the drink-free day marking for a specific date
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use
      required: true
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware
    date:
      name: Date
      description: The date to remove the drink-free day marking (defaults to today)
      required: false
      example: "2025-04-18"
      selector:
        date:

log_sleep_quality:
  name: Log sleep quality
  description: Record sleep quality for a specific date
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use
      required: true
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware
    quality:
      name: Sleep Quality
      description: The quality of sleep to record
      required: true
      example: "average"
      selector:
        select:
          options:
            - label: "Poor"
              value: "poor"
            - label: "Average"
              value: "average"
            - label: "Great"
              value: "great"
          mode: dropdown
    date:
      name: Date
      description: The date to log the sleep quality (defaults to today)
      required: false
      example: "2025-04-18"
      selector:
        date:

refresh:
  name: Refresh data
  description: Manually refresh data from the Drinkaware API
  fields:
    entry_id:
      name: Config Entry ID
      description: The Drinkaware integration to use (leave empty to refresh all integrations)
      required: false
      example: "abc123"
      selector:
        config_entry:
          integration: drinkaware