name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant pytest pytest-asyncio pytest-homeassistant-custom-component pytest-cov
          
      - name: Set up test environment
        run: |
          # Create proper directory structure for the integration
          mkdir -p custom_components/drinkaware
          
          # Copy all component files to custom_components/drinkaware
          cp -r __init__.py config_flow.py const.py sensor.py services.py drink_constants.py dynamic_services.py button.py custom_components/drinkaware/
          
          # Add the integration directory to PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
          
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 custom_components/drinkaware --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 custom_components/drinkaware --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
          
      - name: Run tests
        run: |
          # Display directory structure for debugging
          echo "Custom components directory structure:"
          find custom_components -type f | sort
          
          # Run tests with coverage
          pytest -xvs --cov=custom_components.drinkaware --cov-report=xml tests/
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
