name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant pytest pytest-asyncio pytest-homeassistant-custom-component pytest-cov voluptuous
          
      - name: Set up test environment
        run: |
          mkdir -p custom_components
          # Create the symbolic link correctly
          ln -sf "$(pwd)/custom_components/drinkaware" custom_components/drinkaware
          
          # Create tests/__init__.py if it doesn't exist
          mkdir -p tests/fixtures
          touch tests/__init__.py
          
          # Add test directory to PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
          
      - name: Verify directory structure
        run: |
          echo "Project root structure:"
          ls -la
          
          echo "Custom components structure:"
          ls -la custom_components/
          
          echo "Tests structure:"
          ls -la tests/
          
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 custom_components/drinkaware --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 custom_components/drinkaware --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
          
      - name: Run tests
        run: |
          pytest -xvs tests/
          
      - name: Run tests with coverage
        run: |
          pytest -xvs --cov=custom_components.drinkaware --cov-report=xml tests/
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
